sudo: true
language: java
os:
  - linux
  - osx
script:
  - mvn install
jdk:
  - openjdk6
  - oraclejdk7
  - oraclejdk8
before_install:
  - if [[ $TRAVIS_OS_NAME == osx ]]; then ./travis/before_install-macos.sh; fi
  - if [[ $TRAVIS_OS_NAME == linux ]]; then ./travis/before_install-linux.sh; fi
