sudo: true
language: java
matrix:
  include:
  - os: linux
    jdk: openjdk6
  - os: linux
    jdk: oraclejdk7
  - os: linux
    jdk: oraclejdk8
  - os: osx
script:
  - mvn install
before_install:
  - if [[ $TRAVIS_OS_NAME == osx ]]; then ./travis/before_install-macos.sh; fi
  - if [[ $TRAVIS_OS_NAME == linux ]]; then ./travis/before_install-linux.sh; fi
